### ISSUE TITLE
[Enhancement]: 支持旧版本浏览器

### ISSUE THREAD

**Issue by kimdiego2098** [le5le-com/meta2d.js#246]
### 建议

经测试不支持安卓8.1 ，查了一下没能解决兼容问题，希望官方能支持，下面是报错内容

SyntaxError: Unexpected token .
    at Object.../core/src/core.ts (meta2d.js:260:1)
    at __webpack_require__ (meta2d.js:2022:41)
    at eval (webpack://Le5le/../core/index.ts?:152:67)
    at Object.../core/index.ts (meta2d.js:183:1)
    at __webpack_require__ (meta2d.js:2022:41)
    at eval (webpack://Le5le/./src/index.ts?:22:70)
    at Object../src/index.ts (meta2d.js:1525:1)
    at __webpack_require__ (meta2d.js:2022:41)
    at meta2d.js:2086:37
    at meta2d.js:2089:12

### 建议原因

支持旧版本浏览器

**Comment by ananzhusen** [comment]
建议升级浏览器版本，移动端通过webview方式嵌入，暂不考虑兼容。
